### ISSUE TITLE
Numpy pin does not match pypi package

### ISSUE THREAD

**Issue by scottyhq** [conda-forge/xarray-spatial-feedstock#31]
https://github.com/conda-forge/xarray-spatial-feedstock/blob/5c2e08d16fe82a1c990963d65ae39356eab8b2cf/recipe/meta.yaml#L31 

But after https://github.com/makepath/xarray-spatial/pull/637 over in the main repo requirements.txt removed the numpy pin and added numba cc @ianthomas23 @rabernat .  

Is there a way to read requirements.txt into meta.yml so that they don't get out of sync?

**Comment by ianthomas23** [comment]
@scottyhq Thanks for pointing this out, and sorry we didn't catch it before. PR with rebuild is underway, and I've turned off the automerge so each new release will need a human eyeball to check it in future.

**Comment by scottyhq** [comment]
closed by #32
